### ISSUE TITLE
No Dockerfile?

### ISSUE THREAD

**Issue by IronicBadger** [salihciftci/docps#1]
Why no Dockerfile?!

**Comment by salihciftci** [comment]
Hey Alex,

docps works with host and that's why there is no Dockerfile. But While we're building everything in a container. I will add Dockerfile asap.

**Comment by salihciftci** [comment]
Here it is. 8ee4be903a2836bad5515abfc7455df092ba3fee

It's ready and installation in the README.

**Comment by IronicBadger** [comment]
👍
